spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_shop?createDatabaseIfNotExist=true"
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: debug

company:
  utility:
    enabled: true
  discount:
    enabled: false
  notification:
    email:
      enabled: false
    console:
      enabled: true